### PR TITLE
Syntax highlight using ACE

### PR DESCRIPTION
**Pull request by pgbezerra**
- Add ACE to syntax highlight.

"Compress JSON" and "Check and format JSON" buttons, keeps working and all other features.

syntax error

syntax error send

success

### CODE REVIEW

**Comment by jangaraj** [comment]
Ooops, I've pushed dynamic typeahead/doc dependency on connected Zabbix version => there is a conflict with your feature. Could you resolve it, please?

"Doc" button has a visual (z-index) problem with editor - at least in Firefox:
image

Why do you want to remove "Check & format JSON" button (user doesn't have any "uncompress" option now)? Does your editor work in all major browsers?

**Comment by pgbezerra** [comment]
I'll fix it.

**Comment by pgbezerra** [comment]
z-index fixed, "Check and format" button restored and code rebased.
Thanks!

**Comment by jangaraj** [comment]
LGTM, merging.
Thank you Paulo.

**Pull request merged**
